### ISSUE TITLE
Stuff to fix 

### ISSUE THREAD

**Issue by MrRedstoner** [satalaondrej/PTS1#1]
Code inspection problems in homework.py

1. line 5: spaces around = here violate PEP 8 coding style

1. line 38: No pop exists in dict. Calling remove causes an exception

1.  line 41, 81: Space before : in parameter annotation violates PEP 8 coding style

General:

1. get_relation_class returns a relation, not a class, assignment says `returns a class representing relations on M` (that's how I understand it anyway)

1. Inconsistent type for _relations, usually dict is used, but for exampe line 21 list is used

1. Often a new object is created identical with self, a condition is checked and then this identical object is returned. This is a waste of memory, when no object creation is needed.

1. _relations is often indexed via get() instead of the [] operator.

**Comment by satalaondrej** [comment]
General 2. was mistype, not inconsistency. For general 1 - get_relation_class now returns class, added get_relation_instance that returns instance. Other problems fixed too.
